"""A6 · Paper Writer

Generates a journal-adapted manuscript draft from bibliometric results.
Asks for the target journal, retrieves author guidelines, and produces
a structured .docx following the journal's format requirements.

Outputs:
- paper_draft.docx: manuscript draft
- paper_figures.zip: all figures referenced in the paper
"""

import json
from pathlib import Path
from typing import Any

from biblio_review.agents.base import BaseAgent


class PaperWriter(BaseAgent):
    """Generate journal-adapted manuscript drafts."""

    @property
    def name(self) -> str:
        return "paper_writer"

    @property
    def description(self) -> str:
        return "A6 · Paper writer — Generate journal-adapted manuscript draft"

    def _validate_inputs(self, **kwargs: Any) -> bool:
        metrics_dir = Path(kwargs.get("results", "data/outputs/metrics"))
        if not metrics_dir.exists() or not list(metrics_dir.glob("*.csv")):
            self.console.print("[red]No metrics files found. Run analysis first.[/red]")
            return False
        return True

    def _run(self, **kwargs: Any) -> dict[str, Any]:
        """Generate manuscript draft.

        Flow:
        1. Ask for target journal (or use config)
        2. Load all metrics and results
        3. Generate sections: Introduction, Methods, Results, Discussion, Conclusion
        4. Integrate figures and tables
        5. Format according to journal guidelines
        6. Export as .docx
        """
        metrics_dir = Path(kwargs.get("results", "data/outputs/metrics"))
        viz_dir = Path(kwargs.get("viz", "data/outputs/viz"))
        output_dir = self.ensure_dir("data/outputs/reports")

        # Step 1: Journal selection
        journal = kwargs.get("journal", self.config.paper.target_journal)
        if not journal:
            journal = self.ask_text(
                "Target journal (e.g., 'Scientometrics', 'JMIR', 'npj Digital Medicine')",
                default="Scientometrics",
            )

        self.console.print(f"\nTarget journal: [bold]{journal}[/bold]")

        # Step 2: Load metrics
        metrics = self._load_all_metrics(metrics_dir)
        self.console.print(f"Loaded {len(metrics)} metric files")

        # Step 3: Generate paper sections via LLM
        # TODO: Implement section-by-section generation with LLM
        # Each section uses relevant metrics as evidence
        # The LLM receives structured data, not raw files

        self.console.print("[yellow]Paper generation not yet fully implemented.[/yellow]")
        self.console.print("[dim]This agent will generate each section using the computed metrics.[/dim]")

        # Step 4: Placeholder output
        draft_path = output_dir / "paper_draft.md"
        draft_path.write_text(
            self._generate_outline(journal, metrics),
            encoding="utf-8",
        )

        return {
            "draft_file": str(draft_path),
            "journal": journal,
            "metrics_used": list(metrics.keys()),
        }

    def _load_all_metrics(self, metrics_dir: Path) -> dict[str, Any]:
        """Load all CSV metric files into a dict."""
        import pandas as pd

        metrics = {}
        for csv_file in sorted(metrics_dir.glob("*.csv")):
            try:
                df = pd.read_csv(csv_file)
                metrics[csv_file.stem] = {
                    "columns": list(df.columns),
                    "rows": len(df),
                    "preview": df.head(10).to_dict(orient="records"),
                }
            except Exception as e:
                self.log.warning(f"Could not load {csv_file.name}: {e}")
        return metrics

    def _generate_outline(self, journal: str, metrics: dict) -> str:
        """Generate a paper outline with placeholders."""
        metric_list = "\n".join(f"- {k}: {v['rows']} rows" for k, v in metrics.items())

        return f"""# DRAFT: Bibliometric Review Paper

**Target journal:** {journal}
**Status:** Outline — sections to be generated

## Available metrics

{metric_list}

## Paper structure

### 1. INTRODUCTION
- Context and motivation
- Research gap
- Objectives and research questions (PI1-PI5)

### 2. METHODS
- Study design (bibliometric review)
- Search strategy (PRISMA-S)
- Inclusion/exclusion criteria
- Data sources and corpus
- Analytical techniques
- Software and tools

### 3. RESULTS
- 3.1 Performance analysis (PI1, PI2)
- 3.2 Intellectual structure (PI3)
- 3.3 Social structure (PI2)
- 3.4 Conceptual structure (PI4)
- 3.5 Pre/post GenAI comparison (PI1, PI4)

### 4. DISCUSSION
- Key findings
- Comparison with previous reviews
- Pre/post GenAI impact interpretation
- Research gaps identified (PI5)
- Limitations

### 5. CONCLUSIONS
- Summary of contributions
- Future research agenda
- Practical implications

---
*Generated by biblio-review v0.1.0*
"""
